// Generated by Antigravity for student filtering
frappe.ui.form.on("Student Attendance", {
    refresh: function(frm) {
        frm.set_query("admission_no", function() { return { query: "school.school_management.doctype.student.student.get_active_students" }; });
    },
    onload: function(frm) {
        frm.set_query("admission_no", function() { return { query: "school.school_management.doctype.student.student.get_active_students" }; });
    }
});