// Generated by Antigravity for student filtering
frappe.ui.form.on("Promote", {
    refresh: function(frm) {
        frm.set_query("student_reg_no", "students", function() { return { query: "school.school_management.doctype.student.student.get_active_students" }; });
    },
    onload: function(frm) {
        frm.set_query("student_reg_no", "students", function() { return { query: "school.school_management.doctype.student.student.get_active_students" }; });
    }
});